version: '3.8'

services:
  chrome-webtop:
    build: .
    ports:
      - "12000:6901"
    environment:
      - VNC_PW=password
      - KASM_PORT=6901
    volumes:
      - /dev/shm:/dev/shm
    shm_size: 512mb
    stdin_open: true
    tty: true
    restart: unless-stopped